// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingListWebAPI.Server.Data;

#nullable disable

namespace ShoppingListWebAPI.Server.Migrations
{
    [DbContext(typeof(ShoppingListContext))]
<<<<<<<< HEAD:ShoppingListWebAPI.Server/Migrations/20240223125611_InitialCreate.Designer.cs
    [Migration("20240223125611_InitialCreate")]
========
    [Migration("20240225134900_InitialCreate")]
>>>>>>>> 903f05490efd57c9349cce8a67a3e0fa50eb402c:ShoppingListWebAPI.Server/Migrations/20240225134900_InitialCreate.Designer.cs
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShoppingListWebAPI.Server.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryQuantity = 0,
                            Name = "חלב וביצים"
                        },
                        new
                        {
                            Id = 2,
                            CategoryQuantity = 0,
                            Name = "ירקות ופירות"
                        },
                        new
                        {
                            Id = 3,
                            CategoryQuantity = 0,
                            Name = "מוצרי ניקיון"
                        },
                        new
                        {
                            Id = 4,
                            CategoryQuantity = 0,
                            Name = "מאפים"
                        },
                        new
                        {
                            Id = 5,
                            CategoryQuantity = 0,
                            Name = "בשר ודגים"
                        });
                });

            modelBuilder.Entity("ShoppingListWebAPI.Server.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ShoppingListWebAPI.Server.Models.Product", b =>
                {
                    b.HasOne("ShoppingListWebAPI.Server.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShoppingListWebAPI.Server.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
